#!/usr/bin/env python3
"""Muse Icons 构建脚本。

从 icons.json（唯一数据源）生成：
  - icons/*.svg      标准 SVG 源文件
  - preview/index.html  预览页（深浅双色，数据内联）

用法:
    python scripts/build.py
"""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

SVG_TEMPLATE = (
    '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" '
    'stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round">\n'
    "  {body}\n</svg>\n"
)

PREVIEW_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Muse Icons — Preview</title>
<style>
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body { font-family: -apple-system, "Segoe UI", "PingFang SC", "Microsoft YaHei", sans-serif; background: #FAF9F7; color: #1C1C1E; padding: 48px 24px; }
  header { max-width: 920px; margin: 0 auto 20px; }
  h1 { font-size: 22px; font-weight: 700; }
  header p { color: #8A8A8E; font-size: 13px; margin-top: 6px; }
  .panel { max-width: 920px; margin: 0 auto 16px; border-radius: 18px; padding: 20px 16px 12px; }
  .panel.light { background: #fff; border: 1px solid #ECEAE6; }
  .panel.dark { background: #17171A; }
  .panel h2 { font-size: 12px; letter-spacing: .6px; margin: 0 4px 12px; color: #A0A0A5; }
  .panel.dark h2 { color: #6E6E75; }
  .grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(88px, 1fr)); gap: 2px; }
  .cell { display: flex; flex-direction: column; align-items: center; gap: 8px; padding: 12px 2px; border-radius: 12px; }
  .cell svg { width: 38px; height: 38px; }
  .panel.light .cell { color: #2C2C2E; }
  .panel.dark .cell { color: #EDEDF0; }
  .nm { font-size: 10px; color: #98989D; }
  .panel.dark .nm { color: #66666D; }
  footer { max-width: 920px; margin: 8px auto 0; color: #98989D; font-size: 12px; }
</style>
</head>
<body>
<header>
  <h1>Muse Icons</h1>
  <p>24dp · 1.7dp rounded stroke · MIT · rounded-geometric outline set (work in progress)</p>
</header>
<div class="panel light"><h2>LIGHT</h2><div class="grid" id="g1"></div></div>
<div class="panel dark"><h2>DARK</h2><div class="grid" id="g2"></div></div>
<footer id="meta"></footer>
<script>
const ICONS = __ICONS__;
const render = (id) => {
  document.getElementById(id).innerHTML = Object.entries(ICONS).map(([n, b]) =>
    '<div class="cell"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round">' +
    b + '</svg><div class="nm">' + n + '</div></div>').join('');
};
render('g1');
render('g2');
document.getElementById('meta').textContent = Object.keys(ICONS).length + ' icons · generated by scripts/build.py';
</script>
</body>
</html>
"""


def main() -> None:
    icons = json.loads((ROOT / "icons.json").read_text(encoding="utf-8"))

    svg_dir = ROOT / "icons"
    svg_dir.mkdir(exist_ok=True)
    for name, body in icons.items():
        pretty = body.replace("'", '"').replace("/><", "/>\n  <")
        (svg_dir / f"{name}.svg").write_text(
            SVG_TEMPLATE.format(body=pretty), encoding="utf-8"
        )

    preview_dir = ROOT / "preview"
    preview_dir.mkdir(exist_ok=True)
    page = PREVIEW_TEMPLATE.replace(
        "__ICONS__", json.dumps(icons, ensure_ascii=False)
    )
    (preview_dir / "index.html").write_text(page, encoding="utf-8")

    print(f"built {len(icons)} svg files -> icons/")
    print(f"built preview -> preview/index.html")


if __name__ == "__main__":
    main()
